services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - '5434:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
